#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Change to the AIMAP directory
cd "$SCRIPT_DIR"

# Run the start script
./start








