"""Add AIMAP organisation and metrics models

Revision ID: 3a86383be51c
Revises: 
Create Date: 2025-08-27 14:25:41.271222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a86383be51c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('size_band', sa.String(length=50), nullable=True),
    sa.Column('client_tag', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('ai_tools', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_client_tag'), 'organisations', ['client_tag'], unique=False)
    op.create_index(op.f('ix_organisations_country'), 'organisations', ['country'], unique=False)
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_region'), 'organisations', ['region'], unique=False)
    op.create_index(op.f('ix_organisations_sector'), 'organisations', ['sector'], unique=False)
    op.create_index(op.f('ix_organisations_size_band'), 'organisations', ['size_band'], unique=False)
    op.create_index(op.f('ix_organisations_subsector'), 'organisations', ['subsector'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('ai_adoption_score', sa.Float(), nullable=True),
    sa.Column('maturity_stage', sa.String(length=50), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('benchmark_bucket', sa.String(length=200), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('source_tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_benchmark_bucket'), 'metrics', ['benchmark_bucket'], unique=False)
    op.create_index(op.f('ix_metrics_period'), 'metrics', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_period'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_benchmark_bucket'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_organisations_subsector'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_size_band'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_sector'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_region'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_country'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_client_tag'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
