"""
AIMAP PPTX Export
Generate PowerPoint reports for organisations
"""
import os
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from typing import Dict, List, Optional
from datetime import datetime
from ..models import Organisation, Metrics
from ..scoring.engine import ScoringEngine
from ..config import REPORTS_ROOT

class PPTXReportGenerator:
    """Generate PPTX reports for organisations"""
    
    def __init__(self):
        self.scoring_engine = ScoringEngine()
    
    def generate_report(self, org: Organisation, period: str, logo_path: Optional[str] = None) -> str:
        """Generate a comprehensive PPTX report for an organisation"""
        
        # Get latest metrics
        metrics = Metrics.query.filter_by(
            organisation_id=org.id,
            period=period
        ).first()
        
        if not metrics:
            raise ValueError(f"No metrics found for {org.name} in period {period}")
        
        # Create presentation
        prs = Presentation()
        
        # Slide 1: Title
        self._create_title_slide(prs, org, period)
        
        # Slide 2: Scorecard
        self._create_scorecard_slide(prs, org, metrics)
        
        # Slide 3: Signals Summary
        self._create_signals_slide(prs, org, metrics)
        
        # Slide 4: Peer Benchmark
        self._create_benchmark_slide(prs, org, metrics, period)
        
        # Slide 5: Recommendations
        self._create_recommendations_slide(prs, org, metrics)
        
        # Slide 6: Roadmap
        self._create_roadmap_slide(prs, org, metrics)
        
        # Save presentation
        filename = f"{org.name.replace(' ', '_')}_{period}_report.pptx"
        filepath = REPORTS_ROOT / filename
        prs.save(str(filepath))
        
        return str(filepath)
    
    def _create_title_slide(self, prs: Presentation, org: Organisation, period: str):
        """Create title slide"""
        slide_layout = prs.slide_layouts[0]  # Title slide layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = f"AI Adoption Report"
        subtitle.text = f"{org.name}\n{period}\nGenerated by AIMAP"
    
    def _create_scorecard_slide(self, prs: Presentation, org: Organisation, metrics: Metrics):
        """Create scorecard slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = "AI Adoption Scorecard"
        
        # Add content
        content = slide.placeholders[1]
        tf = content.text_frame
        
        # Overall score
        p = tf.paragraphs[0]
        p.text = f"Overall AI Adoption Score: {metrics.ai_adoption_score:.1f}/100"
        p.font.size = Pt(24)
        p.font.bold = True
        
        # Maturity stage
        p = tf.add_paragraph()
        p.text = f"Maturity Stage: {metrics.maturity_stage}"
        p.font.size = Pt(20)
        
        # Sector and benchmark bucket
        p = tf.add_paragraph()
        p.text = f"Sector: {org.sector}"
        p.font.size = Pt(16)
        
        p = tf.add_paragraph()
        p.text = f"Benchmark Group: {metrics.benchmark_bucket}"
        p.font.size = Pt(16)
        
        # AI Tools count
        ai_tools_count = len(org.ai_tools) if org.ai_tools else 0
        p = tf.add_paragraph()
        p.text = f"AI Tools Detected: {ai_tools_count}"
        p.font.size = Pt(16)
    
    def _create_signals_slide(self, prs: Presentation, org: Organisation, metrics: Metrics):
        """Create signals summary slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = "Key Signals"
        
        content = slide.placeholders[1]
        tf = content.text_frame
        tf.clear()
        
        signals = metrics.signals or {}
        
        # Show top 8 signals
        signal_items = list(signals.items())[:8]
        
        for key, value in signal_items:
            p = tf.add_paragraph()
            p.text = f"• {key.replace('_', ' ').title()}: {value}"
            p.font.size = Pt(14)
        
        # AI Tools detected
        if org.ai_tools:
            p = tf.add_paragraph()
            p.text = f"\nAI Tools Detected:"
            p.font.size = Pt(16)
            p.font.bold = True
            
            for tool in org.ai_tools[:6]:  # Limit to 6 tools
                p = tf.add_paragraph()
                p.text = f"• {tool.title()}"
                p.font.size = Pt(14)
    
    def _create_benchmark_slide(self, prs: Presentation, org: Organisation, metrics: Metrics, period: str):
        """Create peer benchmark slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = "Peer Benchmark"
        
        content = slide.placeholders[1]
        tf = content.text_frame
        tf.clear()
        
        # Get benchmark data
        benchmark_data = self.scoring_engine.get_peer_benchmarks(metrics.benchmark_bucket, period)
        
        p = tf.add_paragraph()
        p.text = f"Benchmark Group: {benchmark_data['bucket']}"
        p.font.size = Pt(16)
        p.font.bold = True
        
        p = tf.add_paragraph()
        p.text = f"Your Score: {metrics.ai_adoption_score:.1f}"
        p.font.size = Pt(14)
        
        p = tf.add_paragraph()
        p.text = f"Peer Median: {benchmark_data['median_score']:.1f}"
        p.font.size = Pt(14)
        
        p = tf.add_paragraph()
        p.text = f"25th Percentile: {benchmark_data['p25_score']:.1f}"
        p.font.size = Pt(14)
        
        p = tf.add_paragraph()
        p.text = f"75th Percentile: {benchmark_data['p75_score']:.1f}"
        p.font.size = Pt(14)
        
        p = tf.add_paragraph()
        p.text = f"Sample Size: {benchmark_data['count']} organizations"
        p.font.size = Pt(14)
        
        # Performance assessment
        your_score = metrics.ai_adoption_score or 0
        median_score = benchmark_data['median_score']
        
        p = tf.add_paragraph()
        if your_score > median_score:
            p.text = f"\n✅ Above peer median by {your_score - median_score:.1f} points"
            p.font.color.rgb = RGBColor(34, 139, 34)  # Forest green
        elif your_score < median_score:
            p.text = f"\n⚠️ Below peer median by {median_score - your_score:.1f} points"
            p.font.color.rgb = RGBColor(255, 140, 0)  # Dark orange
        else:
            p.text = f"\n➡️ At peer median"
        p.font.size = Pt(16)
        p.font.bold = True
    
    def _create_recommendations_slide(self, prs: Presentation, org: Organisation, metrics: Metrics):
        """Create recommendations slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = "Recommendations"
        
        content = slide.placeholders[1]
        tf = content.text_frame
        tf.clear()
        
        # Get recommendations from scoring engine
        if org.sector in self.scoring_engine.sector_adapters:
            adapter = self.scoring_engine.sector_adapters[org.sector]
            features = adapter.extract_features(metrics.signals or {})
            gaps = self.scoring_engine.identify_gaps(features, org.sector)
            recommendations = self.scoring_engine.get_recommendations(org, features, gaps)
        else:
            recommendations = ["Contact AIMAP team for sector-specific recommendations"]
        
        for i, rec in enumerate(recommendations[:6], 1):
            p = tf.add_paragraph()
            p.text = f"{i}. {rec}"
            p.font.size = Pt(14)
    
    def _create_roadmap_slide(self, prs: Presentation, org: Organisation, metrics: Metrics):
        """Create roadmap slide"""
        slide_layout = prs.slide_layouts[1]  # Title and content layout
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        title.text = "90-Day Roadmap"
        
        content = slide.placeholders[1]
        tf = content.text_frame
        tf.clear()
        
        # Generate roadmap based on maturity stage
        stage = metrics.maturity_stage or "Exploring"
        
        roadmap_items = self._get_roadmap_for_stage(stage, org.sector)
        
        for item in roadmap_items:
            p = tf.add_paragraph()
            p.text = f"• {item}"
            p.font.size = Pt(14)
    
    def _get_roadmap_for_stage(self, stage: str, sector: str) -> List[str]:
        """Get roadmap items based on maturity stage"""
        roadmaps = {
            "Exploring": [
                "Conduct AI readiness assessment",
                "Identify pilot use cases",
                "Research relevant AI tools",
                "Define AI governance framework",
                "Plan team training sessions"
            ],
            "Piloting": [
                "Launch first AI pilot project",
                "Measure pilot outcomes",
                "Expand team AI skills",
                "Refine AI policies",
                "Plan scaling strategy"
            ],
            "Scaling": [
                "Deploy successful pilots at scale",
                "Integrate AI into core workflows",
                "Advanced team training",
                "Optimize AI operations",
                "Measure ROI and impact"
            ],
            "Optimizing": [
                "Advanced AI implementations",
                "Cross-functional AI integration",
                "AI innovation projects",
                "Share best practices",
                "Explore emerging AI technologies"
            ],
            "Leading": [
                "Industry thought leadership",
                "AI research partnerships",
                "Innovation lab initiatives",
                "Mentor other organizations",
                "Contribute to AI standards"
            ]
        }
        
        return roadmaps.get(stage, roadmaps["Exploring"])
